### PR TITLE
Add a second cake

### PR DESCRIPTION
**Pull request by adrifelt**
This adds a second cake picture so people can see a different cake sometimes.

### CODE REVIEW

**Comment by adrifelt** [comment]
@meacer PTAL :cake: :cake: :cake:

**Comment by meacer** [comment]
nit: Could use more chocolate. And I hope a real cake will be introduced at some point in the future.

LGTM.

**Comment by adrifelt** [comment]
@meacer any thoughts for how to get a real cake into a git commit? last time i tried i ended up with smooshed cake all over my ethernet port

**Comment by meacer** [comment]
Have you tried using DendoPort? I heard it can commit cakes.

**Comment by moduloprime** [comment]
Wow, I'm pretty impressed you took this bug.

**Comment by adrifelt** [comment]
@moduloprime egm and i had picked out a second cake back when we chose the first. so it's just a 3 line CL to add it. also, i love cake-themed PRs. :cake: :cake: :cake: :balloon: :fireworks:

**Pull request merged**
