### PR TITLE
Only mark "I prefer not to answer" checkboxes as required

### LINKED ISSUE #121: Extension insists I'm female
How to reproduce:
On the survey setup, choose an age. Then click "Submit" without changing anything else.

The extension insist I should check the box that says "Female" to proceed.
survey

### PR DESCRIPTION
**Pull request by adrifelt**
Questions with checkboxes may have required answers.
* If the set of checkboxes include "I prefer not to answer", that should be the required checkbox.
* Otherwise, all checkboxes will be required (although as soon as someone checks any one of them, that is lifted).

Fixes #121

### CODE REVIEW

**Comment by adrifelt** [comment]
@lgarron can you please review this one?

**Comment by lgarron** [comment]
LGTM.

Nice commit message. (But I don't think everyone knows what "Some Default Form 'Lection 'Kwirements" means.)

**Comment by meacer** [comment]
I also like the branch name.

**Comment by adrifelt** [comment]
@meacer I was hoping you'd see ;)

**Pull request merged**
