### PR TITLE
Circled http/https images and question tweaks

### PR DESCRIPTION
**Pull request by moduloprime**
Added screenshots with the relevant symbols circled in red, and changed question text accordingly.
I didn't change the "Would you expect a difference" questions, b/c after further consideration, they lgtm.

### CODE REVIEW

**Comment by adrifelt** [comment]
I don't see the image changes in this PR, is that coming later?

**Comment by adrifelt** [comment]
you might need to do `git mv` or `git add`

**Comment by moduloprime** [comment]
Yup; forgot to do a git add

**Comment by adrifelt** [comment]
lgtm :shipit:

**Pull request merged**
