### PR TITLE
Blurred permission string in extension dialog screenshots

### PR DESCRIPTION
**Pull request by moduloprime**
@adrifelt Pls review

### CODE REVIEW

**Comment by moduloprime** [comment]
Addresses #228

**Comment by adrifelt** [comment]
great thanks!! lgtm

**Comment by meacer** [comment]
Just FYI: Looks like the Windows screenshot was part of the Finch group which added extra text and changed the button labels. It's slightly different than the actual permission dialog.

**Comment by moduloprime** [comment]
Yes, I was wondering about that... but I don't have access to a Windows
machine, so got that screenshot from someone else (rsesek, I think). Know
where we could get a regular Windows screenshot?

**Comment by adrifelt** [comment]
oh good catch @meacer! i have a win machine. can you file a bug? i'll take a new screenshot on win in a bit and post it on the bug so you can then blur it.

**Comment by moduloprime** [comment]
Bug filed: #237

**Pull request merged**
