### PR TITLE
Cut tech literacy questions from eight to four

### PR DESCRIPTION
**Pull request by moduloprime**
uncommented, then cut Captcha, Linux, HTRMB, FAQ

Addresses #213 
@adrifelt pls review

### CODE REVIEW

**Comment by adrifelt** [comment]
hey, a few github tips:

* Use the "Assignee" feature on the right of the PR to assign a reviewer (just assigned myself)
* The title should be a short summary followed by a longer description; right now it's too long to actually fit in the title, so you see it ends up truncated with the remainder spilling into the commit message

**Comment by adrifelt** [comment]
lgtm

**Comment by moduloprime** [comment]
Thx for tips, I am still figuring out git & github. If I use Assignee to assign reviewer, do I still need to put their username in comment?

**Comment by adrifelt** [comment]
nope, itll email me

**Comment by adrifelt** [comment]
hey Rob, i noticed you did'nt actually fix the title or description... it's too late now but in the future please address comments before landing

**Comment by moduloprime** [comment]
I actually thought I did fix the title, so I guess I forgot to save or
something?

**Comment by moduloprime** [comment]
Yeah, that was it... I forgot to save. Fixed.

**Comment by moduloprime** [comment]
So, maybe I should take you up on that github tutorial

**Pull request merged**
